name: Minify Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Minify HTML, CSS and JS files
        run: ./.github/scripts/minify.sh

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Minify source code
          branch: minified-main
          create_branch: true
          push_options: '--force'
